branches:
  only:
  - master

services:
  - docker

script:
  - docker build -t y2khub/docker-bot .
  - echo "$DOCKER_PASSWORD" | docker login -u y2khub --password-stdin
  - docker push y2khub/docker-bot